version: 0.0
os: windows
files:
  - source: https://s3.amazonaws.com/ashantebucket/BuildFiles/CodeDeployCoreDemo/build_output
    destination: C:\inetpub\wwwroot\CodeDeployDemo
  
hooks:
  BeforeInstall:
   - location: .\CreateWebSite.ps1
