version: 0.0
os: windows
files: 
  - 
    destination: "C:\\inetpub\\wwwroot\\CodeDeployDemo"
    source: CodeDeployCoreDemo/build_output
hooks: ~
BeforeInstall:
  - 
    location: /appstop.bat
    runas: administrator
ApplicationStart:
  - 
    location: /appstart.bat
    runas: administrator

