version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CodeDeployCoreDemo/CodeDeployCoreDemo.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o C:/temp/WebApp/CodeDeployDemo CodeDeployCoreDemo/CodeDeployCoreDemo.csproj
artifacts:
  files:
    - C:/temp/WebApp/CodeDeployDemo/**/*
    - scripts/**/*
    - appspec.yml
