version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CodeDeployCoreDemo/CodeDeployCoreDemo.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output CodeDeployCoreDemo/CodeDeployCoreDemo.csproj
artifacts:
  files:
    - CodeDeployCoreDemo/build_output/**/*
    - scripts/**/*
    - appspec.yml
    - buildspec.yml
    - StageArtifact.ps1
    - CreateWebSite.ps1
